package com.logistics;

import com.logistics.core.lib.client.model.ClientModelRegistry;

public final class LogisticsPipeClientModels {
    private static final String[] PIPE_MODELS = {
        "pipe_markings",
        "stone_transport_pipe_core",
        "stone_transport_pipe_arm",
        "stone_transport_pipe_arm_extended",
        "copper_transport_pipe_core",
        "copper_transport_pipe_core_exposed",
        "copper_transport_pipe_core_weathered",
        "copper_transport_pipe_core_oxidized",
        "copper_transport_pipe_arm",
        "copper_transport_pipe_arm_exposed",
        "copper_transport_pipe_arm_weathered",
        "copper_transport_pipe_arm_oxidized",
        "copper_transport_pipe_arm_extended",
        "copper_transport_pipe_arm_extended_exposed",
        "copper_transport_pipe_arm_extended_weathered",
        "copper_transport_pipe_arm_extended_oxidized",
        "gold_transport_pipe_core",
        "gold_transport_pipe_core_powered",
        "gold_transport_pipe_arm",
        "gold_transport_pipe_arm_powered",
        "gold_transport_pipe_arm_extended",
        "gold_transport_pipe_arm_extended_powered",
        "item_extractor_pipe_core",
        "item_extractor_pipe_arm",
        "item_extractor_pipe_arm_extended",
        "item_extractor_pipe_feature",
        "item_extractor_pipe_feature_extended",
        "item_filter_pipe_core",
        "item_filter_pipe_arm",
        "item_filter_pipe_arm_extended",
        "item_insertion_pipe_core",
        "item_insertion_pipe_arm",
        "item_insertion_pipe_arm_extended",
        "item_merger_pipe_core",
        "item_merger_pipe_arm",
        "item_merger_pipe_arm_extended",
        "item_merger_pipe_feature",
        "item_merger_pipe_feature_extended",
        "item_passthrough_pipe_core",
        "item_passthrough_pipe_arm",
        "item_passthrough_pipe_arm_extended",
        "item_void_pipe_core",
        "item_void_pipe_arm",
        "item_void_pipe_arm_extended",
        "basic_logistics_pipe_core",
        "basic_logistics_pipe_arm",
        "basic_logistics_pipe_arm_extended",
        "provider_logistics_pipe_core",
        "provider_logistics_pipe_arm",
        "provider_logistics_pipe_arm_extended",
        "provider_logistics_pipe_feature_extended",
        "requester_logistics_pipe_core",
        "requester_logistics_pipe_arm",
        "requester_logistics_pipe_arm_extended",
        "requester_logistics_pipe_feature",
        "requester_logistics_pipe_feature_extended",
        "supplier_logistics_pipe_core",
        "supplier_logistics_pipe_arm",
        "supplier_logistics_pipe_arm_extended",
        "supplier_logistics_pipe_feature",
        "supplier_logistics_pipe_feature_extended",
        "crafting_logistics_pipe_core",
        "crafting_logistics_pipe_arm",
        "crafting_logistics_pipe_arm_extended",
        "crafting_logistics_pipe_feature_extended",
        "process_logistics_pipe_core",
        "process_logistics_pipe_arm",
        "process_logistics_pipe_arm_extended",
        "satellite_logistics_pipe_core",
        "satellite_logistics_pipe_arm",
        "satellite_logistics_pipe_arm_extended",
        "chassis_logistics_pipe_mk1_core",
        "chassis_logistics_pipe_mk1_arm",
        "chassis_logistics_pipe_mk1_arm_extended",
        "chassis_logistics_pipe_mk2_core",
        "chassis_logistics_pipe_mk2_arm",
        "chassis_logistics_pipe_mk2_arm_extended",
        "chassis_logistics_pipe_mk3_core",
        "chassis_logistics_pipe_mk3_arm",
        "chassis_logistics_pipe_mk3_arm_extended",
        "chassis_logistics_pipe_mk4_core",
        "chassis_logistics_pipe_mk4_arm",
        "chassis_logistics_pipe_mk4_arm_extended",
        "chassis_logistics_pipe_mk5_core",
        "chassis_logistics_pipe_mk5_arm",
        "chassis_logistics_pipe_mk5_arm_extended",
    };

    static {
        for (String name : PIPE_MODELS) {
            ClientModelRegistry.register(LogisticsPipe.model(name));
        }
    }

    public static void init() {}

    private LogisticsPipeClientModels() {}
}
