plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = "${archives_base_name}-${project.name}-${minecraft_version}"
}

java {
    withSourcesJar()
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava(sourceSets.main.java.sourceDirectories.singleFile)
    commonResources(sourceSets.main.resources.sourceDirectories.singleFile)
}
