name: Report an Issue
description: Report a bug, compatibility problem, or performance issue
title: ""
labels: ["bug"]
body:
  - type: textarea
    id: report
    attributes:
      label: Report
      value: |
        ## Summary



        ## Steps to reproduce

        1.
        2.
        3.

        ## Expected



        ## Actual



        ## Environment

        - Logistics:
        - Minecraft:
        - Fabric Loader:
        - Fabric API:
        - Other Mods:

        ## Notes


    validations:
      required: true