package com.logistics;

import com.indemnity83.configory.Config;
import com.indemnity83.configory.ConfigEntries;
import com.indemnity83.configory.ConfigHost;
import com.indemnity83.configory.ConfigKey;
import com.indemnity83.configory.ConfigRegistry;

/**
 * Configory-backed configuration for Logistics.
 *
 * <p>Proof-of-concept scope: only the power/engine domain lives here; the remaining domains still use
 * the legacy {@link com.logistics.core.LogisticsConfig} until they are migrated. To avoid colliding with
 * the legacy {@code config/logistics.json}, the engine keys live on a child config ({@code configFor(MOD_ID,
 * "engines")} → {@code config/logistics/engines.json}); the main {@code logistics} config declares no keys,
 * so bootstrap writes no {@code config/logistics.json}.
 *
 * <p>The in-game {@code /logistics config} surface is generated by configory (see {@link #engines()} and
 * {@code ConfigCommands} in {@link com.logistics.core.LogisticsCommandTree}); the legacy keys will rejoin it
 * once they migrate here.
 */
public final class LogisticsConfigHost implements ConfigHost {
    public static final String MOD_ID = "logistics";

    private static final LogisticsConfigHost INSTANCE = new LogisticsConfigHost();

    private LogisticsConfigHost() {}

    /**
     * Register keys, install cross-field repair, and load from disk. Call once during startup.
     * {@code bootstrapConfig} loads the main config and every child config (here, {@code engines}) and
     * writes defaults to disk on first load — no explicit save needed.
     */
    public static void bootstrap() {
        INSTANCE.bootstrapConfig(MOD_ID);
    }

    /** Typed read of a config value (resolved against the config that owns the key). */
    public static <T> T get(ConfigKey<T> key) {
        return ConfigRegistry.config(key.configId()).get(key);
    }

    /** The engines child config — configory builds the {@code /logistics config} command surface from it. */
    public static Config engines() {
        return ConfigRegistry.config(Configs.REDSTONE_OUTPUT.configId());
    }

    public static final class Configs extends ConfigEntries {
        // Child config → config/logistics/engines.json. No configFor(MOD_ID) here, so the main config stays
        // keyless and bootstrap never writes config/logistics.json (owned by the legacy config for now).
        private static final Config engines = configFor(MOD_ID, "engines");

        private Configs() {}

        public static final ConfigKey<Long> REDSTONE_OUTPUT = engines.defineLong("redstone.output", 10L)
                .min(0L)
                .describe("RF generated per 16-tick interval.")
                .register();

        public static final ConfigKey<Double> STIRLING_MIN_OUTPUT = engines.defineDouble("stirling.min_output", 3.0)
                .min(0.0)
                .maxValueOf(() -> Configs.STIRLING_MAX_OUTPUT)
                .describe("Stirling engine minimum RF/t output.")
                .register();

        public static final ConfigKey<Double> STIRLING_MAX_OUTPUT = engines.defineDouble("stirling.max_output", 10.0)
                .min(0.0)
                .minValueOf(() -> Configs.STIRLING_MIN_OUTPUT)
                .describe("Stirling engine maximum RF/t output.")
                .register();

        /** Cross-field repair belongs to the config the keys live on: heal an inverted range on load (#52). */
        public static void bootstrap(Config config) {
            engines.registerSanitizeHook(() -> engines.repairMinMax(STIRLING_MIN_OUTPUT, STIRLING_MAX_OUTPUT));
        }
    }
}
